-- MySQL Script generated by MySQL Workbench
-- Thu May  5 14:00:45 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`user_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`user_data` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`user_data` (
  `user_data_id` INT NOT NULL AUTO_INCREMENT,
  `avatar` TEXT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido_paterno` VARCHAR(25) NOT NULL,
  `apellido_materno` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_data_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`users` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(30) NOT NULL,
  `user_type` VARCHAR(25) NOT NULL,
  `user_data_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_data_idx` (`user_data_id` ASC),
  CONSTRAINT `fk_users_data`
    FOREIGN KEY (`user_data_id`)
    REFERENCES `biblioteca`.`user_data` (`user_data_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`intereses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`intereses` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`intereses` (
  `interes_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`interes_id`),
  INDEX `fk_intereses_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_intereses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `biblioteca`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `biblioteca`.`admin_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`admin_data` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`admin_data` (
  `admin_data_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `nip` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`admin_data_id`),
  INDEX `fk_admin_data_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_admin_data_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `biblioteca`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`alumnos_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`alumnos_data` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`alumnos_data` (
  `alumno_data_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `carrera` VARCHAR(30) NOT NULL,
  `semestre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`alumno_data_id`),
  INDEX `fk_alumnos_data_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_alumnos_data_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `biblioteca`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`maestros_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`maestros_data` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`maestros_data` (
  `maestro_data_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `carrera` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`maestro_data_id`),
  INDEX `fk_maestros_data_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_maestros_data_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `biblioteca`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`externos_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`externos_data` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`externos_data` (
  `externo_data_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `motivo_visita` TEXT NOT NULL,
  PRIMARY KEY (`externo_data_id`),
  INDEX `fk_externos_data_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_externos_data_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `biblioteca`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`articulos` ;

CREATE TABLE IF NOT EXISTS `biblioteca`.`articulos` (
  `articulo_id` INT NOT NULL,
  `nombre_archivo` TEXT NOT NULL,
  `titulo` VARCHAR(40) NOT NULL,
  `subtitulo` VARCHAR(40) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`articulo_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT 
U.uid, U.correo,
D.avatar, D.nombre, D.apellido_paterno, D.apellido_materno, D.telefono,
A.carrera, A.semestre
FROM users U
JOIN user_data D ON U.user_data_id = D.user_data_id,
JOIN alumnos_data A ON U.user_id = A.user_id;

-- Select DATA From multiles tables 
SELECT * 
FROM users INNER JOIN user_data ON
users.user_data_id = user_data.user_data_id INNER JOIN
alumnos_data ON users.user_id = alumnos_data.user_id
WHERE users.user_id = 1;

